-- MySQL Script generated by MySQL Workbench
-- Sun Nov 21 19:59:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbFamilia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbFamilia` (
  `codFamilia` INT NOT NULL AUTO_INCREMENT,
  `tipoLogradouro` VARCHAR(15) NULL,
  `logradouro` VARCHAR(50) NULL,
  `numero` int NULL,
  `complemento` VARCHAR(20) NULL,
  `bairro` VARCHAR(30) NULL,
  `cep` VARCHAR(10) NULL,
  `municipio` VARCHAR(30) NULL,
  `referencia` VARCHAR(50) NULL,
  `onibus` VARCHAR(10) NULL,
  PRIMARY KEY (`codFamilia`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`tbPessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbPessoas` (
  `codPessoas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `identidade` VARCHAR(20) NULL,
  `cpf` CHAR(11) NULL,
  `situacaoCivil` tinyint NOT NULL,
  `nomeMae` VARCHAR(50) NULL,
  `nomePai` VARCHAR(50) NULL,
  `naturalidade` VARCHAR(20) NULL,
  `atividadeDesenvolvida` VARCHAR(20) NULL,
  `areaInteresseProfissional` VARCHAR(20) NULL,
  `deficiencia` CHAR(1) NULL DEFAULT 'N' COMMENT 'Padrão de resposta \"N\". Em caso de Deficiência, \"S\".',
  `idoso` TINYINT NULL COMMENT 'verdadeiro ou falso',
  `sexo` CHAR(1) NULL COMMENT 'M - Masculino\nF = Feminino',
  `escolaridade` VARCHAR(20) NULL,
  `parentesco` VARCHAR(20) NULL,
  `codFamilia` INT NOT NULL,
  `vinculoFamiliar` tinyint NOT NULL,
  `problemaSaude` CHAR(1) NULL DEFAULT 'N' COMMENT 'Padrão de resposta \"N\". Em caso de problema de saúde, \"S\".',
  PRIMARY KEY (`codPessoas`),
  INDEX `tbPessoas_tbFamilia_idx` (`codFamilia` ASC) VISIBLE,
  CONSTRAINT `tbPessoas_tbFamilia`
    FOREIGN KEY (`codFamilia`)
    REFERENCES `mydb`.`tbFamilia` (`codFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`tbMoradia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbMoradia` (
  `codCaracteristicasMoradia` INT NOT NULL AUTO_INCREMENT,
  `codFamilia` INT NOT NULL,
  `condicaoMoradia` tinyint NULL,
  `numeroComodos` TINYINT NULL,
  `numeroQuartos` TINYINT NULL,
  `banheiro` tinyint NULL,
  PRIMARY KEY (`codCaracteristicasMoradia`),
  INDEX `tbMoradia_tbFamilia_idx` (`codFamilia` ASC) VISIBLE,
  CONSTRAINT `tbMoradia_tbFamilia`
    FOREIGN KEY (`codFamilia`)
    REFERENCES `mydb`.`tbFamilia` (`codFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`tbProblemaSaude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbProblemaSaude` (
  `codProblemaSaude` INT NOT NULL AUTO_INCREMENT,
  `codPessoa` INT NOT NULL,
  `problemaSaude` VARCHAR(45) NOT NULL,
  `medicamento` VARCHAR(45) NOT NULL DEFAULT 'Não',
  `local` VARCHAR(45) NOT NULL,
  `periodicidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codProblemaSaude`),
  INDEX `tbProblemaSaude_tbPessoas_idx` (`codPessoa` ASC) VISIBLE,
  CONSTRAINT `tbProblemaSaude_tbPessoas`
    FOREIGN KEY (`codPessoa`)
    REFERENCES `mydb`.`tbPessoas` (`codPessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`tbDeficiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbDeficiencia` (
  `codDeficiencia` INT NOT NULL AUTO_INCREMENT,
  `codPessoa` INT NOT NULL,
  `deficiencia` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codDeficiencia`),
  INDEX `tbDeficiencia_tbPessoas_idx` (`codPessoa` ASC) VISIBLE,
  CONSTRAINT `tbDeficiencia_tbPessoas`
    FOREIGN KEY (`codPessoa`)
    REFERENCES `mydb`.`tbPessoas` (`codPessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`tbTipoBeneficios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbTipoBeneficios` (
  `codTipoBeneficio` INT NOT NULL AUTO_INCREMENT,
  `beneficio` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codTipoBeneficio`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`tbBeneficio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbBeneficio` (
  `codBeneficio` INT NOT NULL AUTO_INCREMENT,
  `codPessoa` INT NOT NULL,
  `codTipoBeneficio` INT NOT NULL,
  `valorBeneficio` REAL NOT NULL,
  PRIMARY KEY (`codBeneficio`),
  INDEX `codPessoa_idx` (`codPessoa` ASC) VISIBLE,
  INDEX `tbBeneficio_tbTipoBeneficios_idx` (`codTipoBeneficio` ASC) VISIBLE,
  CONSTRAINT `tbbeneficio_tbPessoas`
    FOREIGN KEY (`codPessoa`)
    REFERENCES `mydb`.`tbPessoas` (`codPessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tbBeneficio_tbTipoBeneficios`
    FOREIGN KEY (`codTipoBeneficio`)
    REFERENCES `mydb`.`tbTipoBeneficios` (`codTipoBeneficio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`tbRenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbRenda` (
  `codRenda` INT NOT NULL AUTO_INCREMENT,
  `codPessoas` INT NOT NULL,
  `renda` VARCHAR(10) NOT NULL COMMENT 'Formal ou Informal',
  `valorRenda` REAL NOT NULL,
  PRIMARY KEY (`codRenda`),
  INDEX `tbRenda_tbPessoas_idx` (`codPessoas` ASC) VISIBLE,
  CONSTRAINT `tbRenda_tbPessoas`
    FOREIGN KEY (`codPessoas`)
    REFERENCES `mydb`.`tbPessoas` (`codPessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`tbDocumentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbDocumentos` (
  `codigoDocumento` INT NOT NULL AUTO_INCREMENT,
  `codPessoas` INT NOT NULL,
  `tipodocumento` VARCHAR(30) NOT NULL COMMENT 'Certidão de Nascimento / Certidão de Casamento\nIdentidade\nCPF\nCTPS\nTE',
  `numeroDocumento` VARCHAR(20) NULL,
  PRIMARY KEY (`codigoDocumento`),
  INDEX `tbDocumentos_tbPessoas_idx` (`codPessoas` ASC) VISIBLE,
  CONSTRAINT `tbDocumentos_tbPessoas`
    FOREIGN KEY (`codPessoas`)
    REFERENCES `mydb`.`tbPessoas` (`codPessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`tbVisita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbVisita` (
  `codigoVisita` INT NOT NULL AUTO_INCREMENT,
  `codFamilia` INT NOT NULL,
  `codVoluntario` INT NOT NULL,
  `dataVisita` datetime NOT NULL,
  `alimentacao` VARCHAR(20) NOT NULL DEFAULT 'suficiente',
  `religiaoPredominante` VARCHAR(20) NULL,
  `aguaTratada` VARCHAR(20) NULL,
  `esgotoSanitario` VARCHAR(20) NULL,
  `energiaEletrica` VARCHAR(20) NULL,
  `servicosPublicos` VARCHAR(20) NULL,
  `moradia` VARCHAR(20) NULL,
  `higieneLimpeza` VARCHAR(20) NULL,
  `relacaoFamiliar` VARCHAR(20) NULL,
  `confinamento` VARCHAR(20) NULL,
  `observacoes` VARCHAR(50) NULL,
  PRIMARY KEY (`codigoVisita`),
  INDEX `tbVisita_tbFamilia_idx` (`codFamilia` ASC) VISIBLE,
  CONSTRAINT `tbVisita_tbFamilia`
    FOREIGN KEY (`codFamilia`)
    REFERENCES `mydb`.`tbFamilia` (`codFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tbVisita_tbUsuario`
    FOREIGN KEY (`codVoluntario`)
    REFERENCES `mydb`.`tbUsuario` (`codigoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`tbAberturaFamilia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbAberturaFamilia` (
  `codigoAberturaFamilia` INT NOT NULL AUTO_INCREMENT,
  `codFamilia` INT NOT NULL,
  `dataAbertura` DATE NOT NULL,
  `dataFechamento` DATE NULL,
  `status` VARCHAR(10) NOT NULL COMMENT 'Ativo\nInativo\nCancelado',
  `observacao` VARCHAR(50) NULL,
  `codVoluntario` INT NOT NULL,
  `tipoCesta` VARCHAR(10) NOT NULL COMMENT 'Tipo 1 ou Tipo 2',
  `CorCesta` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codigoAberturaFamilia`),
  INDEX `codfamilia_idx` (`codFamilia` ASC) VISIBLE,
  CONSTRAINT `tbAberturaFamilia_tbFamilia`
    FOREIGN KEY (`codFamilia`)
    REFERENCES `mydb`.`tbFamilia` (`codFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
	CONSTRAINT `tbAberturaFamilia_tbUsuario`
     FOREIGN KEY (`codVoluntario`)
     REFERENCES `mydb`.`tbUsuario` (`codigoUsuario`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`tbFaltas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbFaltas` (
  `codigoFaltas` INT NOT NULL AUTO_INCREMENT,
  `codigoAberturaFamilia` INT NOT NULL,
  `dataFalta` DATE NOT NULL,
  `justificativa` VARCHAR(50) NULL,
  PRIMARY KEY (`codigoFaltas`),
  INDEX `tbFaltas_tbAberturaFamilia_idx` (`codigoAberturaFamilia` ASC) VISIBLE,
  CONSTRAINT `tbFaltas_tbAberturaFamilia`
    FOREIGN KEY (`codigoAberturaFamilia`)
    REFERENCES `mydb`.`tbAberturaFamilia` (`codigoAberturaFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table `mydb`.`tbUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbUsuario` (
  `codigoUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(30) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `tipoUsuario` int NOT NULL COMMENT '1 - Sistema - 2 - Colaborador - 3 - Voluntário',
  `dataCriacao` DATE NOT NULL,
  `status` VARCHAR(10) NOT NULL COMMENT 'Ativo\nInativo',
  PRIMARY KEY (`codigoUsuario`),
  INDEX `codigoUsuario_idx` (`codigoUsuario` ASC) VISIBLE)
ENGINE = InnoDB;